# Generated by Django 5.2.11 on 2026-04-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=20)),
                ('course_number', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('crn', models.CharField(max_length=20, unique=True)),
                ('term', models.CharField(max_length=20)),
                ('instructor', models.CharField(blank=True, max_length=200)),
                ('schedule_type', models.CharField(blank=True, max_length=50)),
                ('campus', models.CharField(blank=True, max_length=100)),
                ('seats_available', models.IntegerField(default=0)),
                ('max_enrollment', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=200)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('schedule_type', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_times', to='halls.course')),
            ],
        ),
    ]
